import pyodbc
import pandas as pd
import time
import datetime

def run_procedure():
    export_db = r"C:\InventoryBalanceData\Prepared_Reps"
    # Created a pyodbc connection to db electrolux
    conn = pyodbc.connect('DRIVER={SQL Server};'
                          'SERVER=DT-SupplyPlanning-EU.biz.electrolux.com;Trusted_Connection=no;'
                          'Database=SupplyPlanning_Test;'
                          'UID=supply_admin;'
                          'PWD={i)Z\#6&;~fwJNZ7e}')

    cursor = conn.cursor()
    sql_query = pd.read_sql_query("""
        WITH GROSS_FORECAST
    AS (
    SELECT [GROSS].[#1]
          ,[GROSS].[Plant]
          ,[GROSS].[ANC]
          ,[GROSS].[Description]
          ,[GROSS].[BC]
          , CASE WHEN [SAP_Code].[Supplier_Code] IS NOT NULL THEN [SAP_Code].[Supplier_Code]
            WHEN [IDW_GROSS].[Supplier] IS NOT NULL THEN [IDW_GROSS].[Supplier]
            ELSE '-'
            END AS [Supplier]
          , CASE WHEN [SAP_Name].[Supplier_Description] IS NOT NULL THEN [SAP_Name].[Supplier_Description]
            -- WHEN [IDW_GROSS].[Local_Supplier] IS NOT NULL THEN [IDW_GROSS].[PMS_Supplier]
            WHEN [IDW_GROSS].[Local_Supplier] IS NOT NULL THEN [IDW_GROSS].[Local_Supplier]
            ELSE '-'
            END AS [Local_Supplier]
          , CASE WHEN [IDW_Costs].[Conv_STK3_Calc] IS NOT NULL THEN [IDW_Costs].[Conv_STK3_Calc]
            WHEN [DCDE].[STK3_EUR] IS NOT NULL THEN [DCDE].[STK3_EUR]
            WHEN [SAP_Cost].[Standard_Cost] IS NOT NULL THEN [SAP_Cost].[Standard_Cost]
            WHEN [IDW_GROSS].[DM] IS NOT NULL THEN [IDW_GROSS].[DM]
            ELSE 0
            END AS [DM]
          , CASE WHEN [IDW_GROSS].[IDCO] IS NOT NULL THEN [IDW_GROSS].[IDCO]
            WHEN [IDW_Costs].[IDCO] IS NOT NULL THEN [IDW_Costs].[IDCO]
            WHEN [SAP_IDCO].[IDCO_Description] IS NOT NULL THEN [SAP_IDCO].[IDCO_Description]
            ELSE '-'
            END AS [IDCO]
          ,[GROSS].[wk0]
          ,[GROSS].[wk1]
          ,[GROSS].[wk2]
          ,[GROSS].[wk3]
          ,[GROSS].[wk4]
          ,[GROSS].[wk5]
          ,[GROSS].[wk6]
          ,[GROSS].[wk7]
          ,[GROSS].[wk8]
          ,[GROSS].[wk9]
          ,[GROSS].[wk10]
          ,[GROSS].[wk11]
          ,[GROSS].[wk12]
          ,[GROSS].[wk13]
          ,[GROSS].[wk14]
          ,[GROSS].[wk15]
          ,[GROSS].[wk16]
          ,[GROSS].[wk17]
          ,[GROSS].[wk18]
          ,[GROSS].[wk19]
          ,[GROSS].[wk20]
          ,[GROSS].[wk21]
          ,[GROSS].[wk22]
          ,[GROSS].[wk23]
          ,[GROSS].[wk24]
          ,[GROSS].[wk25]
          ,[GROSS].[wk26]
          ,[GROSS].[wk27]
          ,[GROSS].[wk28]
          ,[GROSS].[wk29]
          ,[GROSS].[wk30]
          ,[GROSS].[wk31]
          ,[GROSS].[wk32]
          ,[GROSS].[wk33]
          ,[GROSS].[wk34]
          ,[GROSS].[wk35]
          ,[GROSS].[wk36]
          ,[GROSS].[wk37]
          ,[GROSS].[wk38]
          ,[GROSS].[wk39]
          ,[GROSS].[wk40]
          ,[GROSS].[wk41]
          ,[GROSS].[wk42]
          ,[GROSS].[wk43]
          ,[GROSS].[wk44]
          ,[GROSS].[wk45]
          ,[GROSS].[wk46]
          ,[GROSS].[wk47]
          ,[GROSS].[wk48]
          ,[GROSS].[wk49]
          ,[GROSS].[wk50]
          ,[GROSS].[wk51]
          ,[GROSS].[wk52]
          ,[GROSS].[wk53]
      FROM [SupplyPlanning_Test].[dbo].[temp_data_gross_forecast] as [GROSS]
      LEFT JOIN [SupplyPlanning_Test].[dbo].[temp_data_SAP_Supplier_Code] as [SAP_Code]
      ON [GROSS].[#1] = [SAP_Code].[#]
      LEFT JOIN [SupplyPlanning_Test].[dbo].[temp_data_gross_forecast] as [IDW_GROSS]
      ON [GROSS].[#1] = [IDW_GROSS].[#1]
      LEFT JOIN [SupplyPlanning_Test].[dbo].[temp_data_SAP_Supplier_Description] as [SAP_Name]
      ON [GROSS].[#1] = [SAP_Name].[#]
      LEFT JOIN [SupplyPlanning_Test].[dbo].[temp_data_IDW_cost] as [IDW_Costs]
      ON [GROSS].[#1] = [IDW_Costs].[#1]
      LEFT JOIN  [SupplyPlanning_Test].[dbo].[temp_data_DCDE_support_table] as [DCDE]
      ON [GROSS].[#1] = [DCDE].[#]
      LEFT JOIN [SupplyPlanning_Test].[dbo].[temp_data_SAP_Cost] as [SAP_Cost]
      ON [GROSS].[#1] = [SAP_Cost].[#]
      LEFT JOIN [SupplyPlanning_Test].[dbo].[temp_data_SAP_Supplier_IDCO] as [SAP_IDCO]
      ON [GROSS].[ANC] = [SAP_IDCO].[Product_ID]
    )
    ,GROSS_FORECAST_SUPP_PLANT AS (
        SELECT
           [GROSS_FORECAST].[#1]
          ,[GROSS_FORECAST].[Supplier] + [Plant] AS [#2]
          ,[GROSS_FORECAST].[Plant]
          ,[GROSS_FORECAST].[ANC]
          ,[GROSS_FORECAST].[Description]
          ,[GROSS_FORECAST].[BC]
          ,[GROSS_FORECAST].[Supplier]
          ,[GROSS_FORECAST].[Local_Supplier]
          ,[GROSS_FORECAST].[DM]
          ,[GROSS_FORECAST].[IDCO]
          ,[GROSS_FORECAST].[wk0]
          ,[GROSS_FORECAST].[wk1]
          ,[GROSS_FORECAST].[wk2]
          ,[GROSS_FORECAST].[wk3]
          ,[GROSS_FORECAST].[wk4]
          ,[GROSS_FORECAST].[wk5]
          ,[GROSS_FORECAST].[wk6]
          ,[GROSS_FORECAST].[wk7]
          ,[GROSS_FORECAST].[wk8]
          ,[GROSS_FORECAST].[wk9]
          ,[GROSS_FORECAST].[wk10]
          ,[GROSS_FORECAST].[wk11]
          ,[GROSS_FORECAST].[wk12]
          ,[GROSS_FORECAST].[wk13]
          ,[GROSS_FORECAST].[wk14]
          ,[GROSS_FORECAST].[wk15]
          ,[GROSS_FORECAST].[wk16]
          ,[GROSS_FORECAST].[wk17]
          ,[GROSS_FORECAST].[wk18]
          ,[GROSS_FORECAST].[wk19]
          ,[GROSS_FORECAST].[wk20]
          ,[GROSS_FORECAST].[wk21]
          ,[GROSS_FORECAST].[wk22]
          ,[GROSS_FORECAST].[wk23]
          ,[GROSS_FORECAST].[wk24]
          ,[GROSS_FORECAST].[wk25]
          ,[GROSS_FORECAST].[wk26]
          ,[GROSS_FORECAST].[wk27]
          ,[GROSS_FORECAST].[wk28]
          ,[GROSS_FORECAST].[wk29]
          ,[GROSS_FORECAST].[wk30]
          ,[GROSS_FORECAST].[wk31]
          ,[GROSS_FORECAST].[wk32]
          ,[GROSS_FORECAST].[wk33]
          ,[GROSS_FORECAST].[wk34]
          ,[GROSS_FORECAST].[wk35]
          ,[GROSS_FORECAST].[wk36]
          ,[GROSS_FORECAST].[wk37]
          ,[GROSS_FORECAST].[wk38]
          ,[GROSS_FORECAST].[wk39]
          ,[GROSS_FORECAST].[wk40]
          ,[GROSS_FORECAST].[wk41]
          ,[GROSS_FORECAST].[wk42]
          ,[GROSS_FORECAST].[wk43]
          ,[GROSS_FORECAST].[wk44]
          ,[GROSS_FORECAST].[wk45]
          ,[GROSS_FORECAST].[wk46]
          ,[GROSS_FORECAST].[wk47]
          ,[GROSS_FORECAST].[wk48]
          ,[GROSS_FORECAST].[wk49]
          ,[GROSS_FORECAST].[wk50]
          ,[GROSS_FORECAST].[wk51]
          ,[GROSS_FORECAST].[wk52]
          ,[GROSS_FORECAST].[wk53] 
    FROM GROSS_FORECAST
    ),
    GROSS_FORECAST_FINISH AS (
        SELECT
           [GROSS_FORECAST_SUPP_PLANT].[#1]
          ,[GROSS_FORECAST_SUPP_PLANT].[#2]
          ,[GROSS_FORECAST_SUPP_PLANT].[Plant]
          ,[GROSS_FORECAST_SUPP_PLANT].[ANC]
          ,[GROSS_FORECAST_SUPP_PLANT].[Description]
          ,[GROSS_FORECAST_SUPP_PLANT].[BC]
          ,[GROSS_FORECAST_SUPP_PLANT].[Supplier]
          ,CASE 
          WHEN [SAP_Suppliers].[Supplier_Description] IS NOT NULL THEN [SAP_Suppliers].[Supplier_Description]
          WHEN [GROSS_FORECAST_SUPP_PLANT].[Local_Supplier] IS NOT NULL THEN [GROSS_FORECAST_SUPP_PLANT].[Local_Supplier]
          ELSE '-'
          END AS [Local_Supplier]
        --   ,[GROSS_FORECAST_SUPP_PLANT].[Local_Supplier]
          ,[GROSS_FORECAST_SUPP_PLANT].[DM]
          ,[GROSS_FORECAST_SUPP_PLANT].[IDCO]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk0]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk1]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk2]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk3]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk4]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk5]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk6]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk7]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk8]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk9]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk10]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk11]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk12]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk13]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk14]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk15]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk16]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk17]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk18]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk19]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk20]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk21]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk22]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk23]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk24]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk25]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk26]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk27]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk28]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk29]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk30]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk31]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk32]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk33]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk34]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk35]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk36]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk37]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk38]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk39]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk40]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk41]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk42]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk43]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk44]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk45]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk46]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk47]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk48]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk49]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk50]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk51]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk52]
          ,[GROSS_FORECAST_SUPP_PLANT].[wk53] 
        FROM GROSS_FORECAST_SUPP_PLANT
        LEFT JOIN (SELECT DISTINCT [#.1]
            ,[Supplier_Description]
            FROM [SupplyPlanning_Test].[dbo].[temp_data_SAP_Suppliers])
            as [SAP_Suppliers]
        ON [GROSS_FORECAST_SUPP_PLANT].[#2] = [SAP_Suppliers].[#.1]
    )
    SELECT  * FROM  GROSS_FORECAST_FINISH
    """, conn)
    print(sql_query)
    conn.commit()
    exportDF = sql_query.to_csv(export_db +  '\\Gross_Forecast_' + time.strftime('%Y%m%d') +'.csv', encoding='utf-8', index=False)
